# Generated by Django 5.0.6 on 2024-06-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cloice',
            new_name='Choice',
        ),
    ]
