# Generated by Django 5.0.6 on 2024-06-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_cloice_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
